version: '3.7'

services:
  jormungandr-rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=MGBACON
      - RABBITMQ_DEFAULT_PASS=NEEDSTEA
    networks:
      - default
      ports:
        - 15672:15672
        - 5672:5672